the-loom/dashboard

app/controllers/notifications_controller.rb, app/models/membership.rb, app/models/notification.rb, app/policies/notification_policy.rb, app/views/layouts/application.html.erb, app/views/notifications/index.html.erb, app/views/notifications/new.html.erb, config/routes.rb, db/migrate/20180219143000_create_notification.rb, db/schema.rb, spec/models/notification_spec.rb
Es un flujo básico, con algunas falencias para identificar qué notificaciones han sido leídas.
Pero por el momento, funciona bien y barato.
=> Se agrega flujo para Notificaciones

app/controllers/peer_review/challenges_controller.rb, app/models/peer_review/challenge.rb, app/views/peer_review/challenges/form.html.erb
- Se arreglo error si un campo esta vació al editar o crear un nuevo desafió
- Se agrego validación a la dificultad en el modelo
- Se cambio el form por simple_form
=> Challenges

app/controllers/exercises_controller.rb, app/controllers/multiple_choices/questionnaires_controller.rb, app/controllers/peer_review/challenges_controller.rb, app/controllers/resource_categories_controller.rb, app/controllers/resources_controller.rb, app/controllers/tiny_cards/decks_controller.rb, app/models/course.rb, app/models/resource.rb, app/models/resource_category.rb, app/policies/resource_policy.rb, app/views/admin/courses/form.html.erb, app/views/layouts/_menu.html.erb, app/views/resource_categories/form.html.erb, app/views/resource_categories/index.html.erb, app/views/resources/form.html.erb, app/views/resources/index.html.erb, app/views/shared/_actions.html.erb, config/locales/es.yml, config/routes.rb, db/migrate/20200324144029_create_resources.rb, db/schema.rb, lib/publisher.rb
Referencia: https://trello.com/c/4SbgRZ8T/208-covid-posibilidad-de-enlazar-material-a-loom
Siempre necesitamos enlazar material. Esta es una primera aproximación. ¡Se escuchan sugerencias de mejora!
=> Added Resources/ResourceCategories and corresponding CRU[D]s

app/assets/stylesheets/application.css
Reverts the-loom/dashboard#227
=> Revert "Se configura la altura por defecto del trix-editor"

app/models/event.rb, app/views/events/form.html.erb
https://trello.com/c/y5T60eLN/238-validaci%C3%B3n-de-los-puntos-en-evento
=> Validación de puntos del evento

aplicación/ vistas/ peer_review/ desafíos/overview.html.erb, app/controllers/peer_review/challenges_controller.rb, app/helpers/percentage_helper.rb, app/models/peer_review/challenge.rb, app/views/peer_review/challenges/form.html.erb, app/views/peer_review/challenges/index.html.erb, app/views/peer_review/challenges/overview.html.erb, app/views/shared/_difficulty.html.erb, db/migrate/20200416121851_add_expected_reviews_to_peer_review_challenge.rb, db/schema.rb
Ref: [Trello](https://trello.com/c/8YM4hUbV/258-expected-reviews-prch)
=> Expected reviews for Peer Review Challenges

app/controllers/peer_review/solutions_controller.rb, app/models/peer_review/review.rb
Ref: [Trello](https://trello.com/c/gPX0fttu/260-si-ingreso-a-panorama-revisar-una-soluci%C3%B3n-que-ya-estoy-revisando-abrir-esa-y-no-crear-una-nueva)
=> Prevents reviewing same solution twice

app/controllers/application_controller.rb, app/controllers/badges_controller.rb, app/controllers/peer_review/solutions_controller.rb, app/controllers/teachers_controller.rb, app/helpers/dates_helper.rb
Running rubocop from time to time...
=> Rubocop rulez

.githooks/pre-commit, app/controllers/peer_review/challenges_controller.rb, app/controllers/peer_review/solutions_controller.rb, app/models/peer_review/challenge.rb, app/services/solution_finder.rb, app/views/peer_review/challenges/form.html.erb, app/views/peer_review/challenges/overview.html.erb, app/views/peer_review/challenges/show.html.erb, app/views/peer_review/solutions/new.html.erb, app/views/peer_review/solutions/show.html.erb, db/migrate/20200424222419_add_team_challenge_to_peer_review_challenges.rb, db/schema.rb
Ref: [Trello](https://trello.com/c/7kYdBWLj/289-teams-solutions)
Necesitamos un hack rápido para tener tareas por grupo. Para no inventar una nueva clase, con todos sus controllers, lo que decidimos fue implementar (en tiempo récord) la posibilidad de compartir una solución si sos parte del mismo grupo, si el desafío lo permite.
Por ahora sólamente se habilita para **desafíos de revisión por docentes**.
=> Team challenges

app/views/peer_review/challenges/index.html.erb
https://trello.com/c/kYmY9SdB/98-unificar-acciones-de-cancelacion-habilitacion-borrado-visualizacion-etc
=> Cambio de botones para desafío

app/controllers/peer_review/challenges_controller.rb, app/models/course.rb, app/presenters/peer_review_challenge_solver_stats.rb, app/views/peer_review/challenges/overview.html.erb
Ref: [Trello](https://trello.com/c/Xkz3Aa40/)
Queremos agregar a todos los estudiantes al panorama, para visualmente saber quiénes lo han terminado y quiénes no.
No deberían ser sólamente los estudiantes, ya que hay docentes que resuelven desafíos para poner respuestas correctas o erróneas a propósito
=> Show all course members in overview

app/controllers/courses_controller.rb, app/controllers/sessions_controller.rb, app/models/user.rb, db/migrate/20200430125021_add_last_course_visited_to_user.rb, db/schema.rb
Ref: [Trello](https://trello.com/c/F1OH2LiB/266-cuando-salgo-volver-al-ultimo-curso-al-que-habia-entrado-agregar-un-id-en-algun-lado)
Queremos redirigir al estudiante al último curso que se haya visitado, para evitar los errores frecuentes de buscar las cosas en el curso equivocado
=> Allows redirection to last visited course

app/controllers/peer_review/solutions_controller.rb, app/models/peer_review/challenge.rb, app/models/peer_review/solution.rb, app/views/dashboard/index.html.erb, app/views/peer_review/challenges/overview.html.erb, app/views/peer_review/challenges/show.html.erb, app/views/peer_review/solutions/show.html.erb, config/routes.rb, db/migrate/20200430131646_add_picked_to_peer_review_solutions.rb, db/schema.rb
Ref: [Trello](https://trello.com/c/rPr1ToI3/301-agregar-solucion-sugerida-en-los-prch-profe-marca-una-solucion-como-ideal)
Se pretende mostrar soluciones escogidas a los ejercicios, para mejorar el nivel de feedback que damos a los estudiantes
=> Allows solution picking/unpicking

app/views/teams/index.html.erb
Ref: [Trello](https://trello.com/c/W1vGtjly/322-sacar-gh-repo-de-los-equipos)
=> Removes misleading github repo URL

app/controllers/peer_review/challenges_controller.rb, app/views/peer_review/challenges/index.html.erb, config/routes.rb, db/migrate/20200512115923_add_awarded_to_challenge.rb, db/schema.rb
Ref: [Trello](https://trello.com/c/vAZkqD3x/331-script-para-otorgar-premios-sobre-tareas-normales-de-revision-360)
Estamos premiando algunos desafíos. Quizás falten validaciones, y probablemente haya que permitir una configuración de puntajes en un mediano plazo.
=> Awards challenges unless already awarded

LICENSE
Estamos cambiando la licencia de Loom, para proteger los intereses de los usuarios y evitar de forma explícita usos no deseados de la plataforma.
Loom nació del esfuerzo bienintencionado. Con el espíritu del software libre, nos proponemos brindar una herramienta útil, y a cambio recibir actualizaciones y mejoras que puedan implementarse, si fueran de interés para la comunidad.
Una versión reducida de la nueva licencia puede encontrarse en la parte superior de esta página:
https://choosealicense.com/licenses/agpl-3.0
La licencia anterior, en cambio, tenía las siguientes características:
https://choosealicense.com/licenses/mit
Y era, evidentemente, demasiado laxa. Cambios:
1. Ahora las contribuciones ceden derechos al repositorio principal. Esto incluye colaboradores externos, como así …
=> Changed MIT for AGPL3

app/controllers/peer_review/challenges_controller.rb, app/models/peer_review/challenge.rb, app/views/dashboard/index.html.erb, app/views/peer_review/challenges/form.html.erb, app/views/peer_review/challenges/index.html.erb, db/migrate/20200521144859_add_optional_to_challenges.rb, db/migrate/20200521144859_add_optional_to_challengues.rb, db/schema.rb
https://trello.com/c/jsOFyQQd/263-prch-ejercicios-opcionales
=> PRCH opcional

app/views/peer_review/challenges/index.html.erb
https://trello.com/c/iRQYyzWZ/268-separar-publicados-de-no-publicados
=> Publish PRCH

app/presenters/peer_review_challenge_solver_stats.rb, app/views/peer_review/challenges/overview.html.erb
https://trello.com/c/csWqjOIb/317-saber-si-una-solucion-tiene-revisiones-de-profesor-y-quien-desde-el-panorama
=> PRCH Review Teacher in overview

app/views/admin/courses/index.html.erb, app/views/badges/index.html.erb, app/views/competence_tags/index.html.erb, app/views/events/index.html.erb, app/views/exercises/index.html.erb, app/views/lectures/index.html.erb, app/views/multiple_choices/questionnaires/index.html.erb, app/views/multiple_choices/questionnaires/show.html.erb, app/views/notifications/index.html.erb, app/views/repos/index.html.erb, app/views/teams/index.html.erb, app/views/tiny_cards/decks/index.html.erb, app/views/tiny_cards/decks/show.html.erb
Ref: [Trello](https://trello.com/c/WnXIJXYw/239-problemas-en-el-dise%C3%B1o)
Se busca uniformar la interfaz para facilitar la migración a Bootstrap 4
=> New button is now left-aligned for all features

app/controllers/admin/users_controller.rb, app/controllers/sessions_controller.rb, app/models/user.rb, app/presenters/peer_review_challenge_solver_stats.rb, app/views/pages/welcome.html.erb, app/views/peer_review/challenges/overview.html.erb, config/routes.rb
[Trello 1](https://trello.com/c/P3nxZSuM/283-%E2%9A%99%EF%B8%8F-para-desarrollo-deber%C3%ADa-haber-un-login-que-no-necesite-de-github-google), [Trello 2](https://trello.com/c/1IusTJjk/386-segurizar-acciones-de-admin-el-listado-de-usuarios-se-ve-dde-afuera), [Trello 3](https://trello.com/c/y5tv2FD3/389-agregar-equipo-en-vista-panorama-para-filtrar-m%C3%A1s-f%C3%A1cil)
- Se seguriza ruta de admin. Inofensiva pero leaky
- Se agrega un login para admin en desarrollo (para evitar el paso por OAuth)
- Se agrega columna de equipos al panorama
- Se eliminan datos innecesarios del panorama (revisiones en borrador)
=> Second batch of enhancements

app/assets/javascripts/application2.js, app/controllers/peer_review/solutions_controller.rb, app/services/solution_finder.rb, app/views/layouts/application2.html.erb, app/views/peer_review/challenges/show.html.erb, app/views/peer_review/solutions/new.html.erb, config/routes.rb
Ref: [Trello 1](https://trello.com/c/m7mStXI1/365-poner-info-del-desafio-dentro-del-desafio-opcional-fecha-dificultad-blah) & [Trello 2](https://trello.com/c/WqGuC0z7/368-agregar-boton-para-publicar-dde-el-panorama-del-ejercicio-para-el-estudiante)
En un intento por mejorar la usabilidad del proceso de publicación, sólo se permite guardar borradores. Ahora se publica desde fuera de la solución, para así estar seguro de que se guardó correctamente todo (adjuntos incluidos).
=> Reorganized PeerReview::Challenge show screen

app/controllers/notifications_controller.rb, app/controllers/peer_review/reviews_controller.rb, app/models/membership.rb, app/models/notification.rb, app/models/peer_review/review.rb, db/migrate/20200603131757_add_receiver_to_notifications.rb, db/schema.rb, lib/tasks/purge_notifications.rake
Ref: [Trello](https://trello.com/c/mKTlsPza/334-notificaciones-a-individuos)
Queremos poder enviar notificaciones personalizadas, para que los estudiantes sepan cuándo sucede algo.
Esto nos permite avisar cuando están por vencer ejercicios, cuando tienen una revisión disponible, etc.
=> Feature / Notifications for individuals

app/views/layouts/_menub4.html.haml, app/views/layouts/_navbar.html.haml, app/views/layouts/application2.html.erb
Ref: [Trello](https://trello.com/c/7cIoE5eG/393-menu-en-el-nuevo-layout)
Migramos el componente a la nueva representación de frontend. Feedback de @Federico-G es más que bienvenido :)
=> Bootstrap 4 navbar

app/controllers/suggestions_controller.rb, app/views/suggestions/index.html.haml, app/views/suggestions/show.html.haml, config/locales/es.yml, config/routes.rb
Ref: [Trello](https://trello.com/c/xxZsbo9J/378-las-sugerencias-necesitan-tener-el-show-que-muestre-todos-los-detalles-y-libere-muchas-cosas-de-la-pantalla-del-listado)
Se agrega una visualización con más datos sobre las sugerencias recibidas.
Se libera un poco la pantalla del "índice"
=> Added Suggestion/show

app/presenters/peer_review/overview_presenter.rb
Ref: [Trello](https://trello.com/c/vPBFaSOz/391-revisar-calculo-de-total-de-posibles-revisiones)
Se cambia el cálculo de revisiones esperadas.
=> Fixed: Expected reviews in Challenge Overview

app/views/peer_review/challenges/index.html.erb
Ref: [Trello](https://trello.com/c/e6f6OIW7/297-ui-se-puede-cambiar-datatables-para-que-en-lugar-de-registros-diga-desafios-etc)
=> UI enhancements for DataTables

app/controllers/peer_review/challenges_controller.rb, app/models/peer_review/challenge.rb, app/presenters/peer_review_challenges_stats.rb, app/views/peer_review/challenges/index.html.erb
Ref: [Trello](https://trello.com/c/xFRMn43n/405-necesitamos-descargar-el-panorama-de-practicas)
=> Descargar panorama de practicas

Makefile, app/models/badge.rb, app/models/peer_review/review.rb, app/views/peer_review/challenges/show.html.erb, app/views/peer_review/solutions/show.html.erb, app/views/users/index.html.erb
Ref: [Trello](https://trello.com/c/eOY9wnLs/255-%E2%9A%99%EF%B8%8F-mover-los-where-de-vistas-a-controllers-al-menos)
Bajamos la repetición de código si utilizamos scopes.
=> Maintenance: we move .where away from views to increase maintenance

app/assets/stylesheets/application2.css, app/controllers/peer_review/reviews_controller.rb, app/controllers/peer_review/solutions_controller.rb, app/views/layouts/_menub4.html.haml, app/views/layouts/application2.html.erb, app/views/peer_review/reviews/new.html.erb, app/views/peer_review/solutions/new.html.erb
Ref: [Trello](https://trello.com/c/IDiEFBzW/394-ui-resolver-ejercicio-nuevo-layout)
=> UI/PeerReview::Solution/Review with Bootstrap 4

app/controllers/application_controller.rb, app/controllers/multiple_choices/questionnaires_controller.rb, app/presenters/multiple_choices/practice_question_presenter.rb, app/presenters/multiple_choices/practice_questionnaire_presenter.rb, app/presenters/multiple_choices/solved_question_presenter.rb, app/presenters/multiple_choices/solved_questionnaire_presenter.rb, app/views/multiple_choices/questionnaires/practice.html.erb
Ref: [Trello](https://trello.com/c/GBRplwbd/206-mch-mezclar-aleatoriamente-las-rtas-y-las-preguntas-cada-vez-mantener-el-orden-entre-practica-y-nota)
Queremos mostrar los cuestionarios con las preguntas en diferente orden, y las respuestas también. Pero queremos mantener el aspecto visual para los estudiantes.
=> Randomized questions and answers for MultipleChoice::Questionnaires

app/helpers/difficulty_helper.rb, app/models/automatic_correction/repo.rb, app/models/exercise.rb, app/models/peer_review/challenge.rb, app/views/exercises/index.html.erb, app/views/peer_review/challenges/index.html.erb, app/views/peer_review/challenges/show.html.erb, app/views/repos/index.html.erb, lib/has_difficulty.rb
Ref: [Trello](https://trello.com/c/XvMh1XKV/261-%E2%9A%99%EF%B8%8F-cambiar-validaci%C3%B3n-de-dificultad)
Externalizamos la dificultad, para poder reutilizar código.
=> New module: HasDifficulty. Includes validations and some useful scopes

app/controllers/admin/users_controller.rb, app/controllers/application_controller.rb, app/controllers/sessions_controller.rb
Ref: [Trello](https://trello.com/c/MHJAmmjJ/417-bug-cuando-personifico-a-alguien-de-otro-curso-falla-cambiar-el-curso-al-personificar)
Utiliza el mecanismo normal de login cuando se personifica un usuario.
=> Fixed error when impersonating users in different courses

app/controllers/peer_review/solutions_controller.rb, app/views/peer_review/_info_box.html.erb, app/views/peer_review/challenges/show.html.erb, app/views/peer_review/solutions/show.html.erb
Ref: [Trello](https://trello.com/c/WVbZ9Jw0/412-prchsolution-show-con-bootstrap-4)
=> Updated PeerReview::Solution#show to Bootstrap 4

app/controllers/multiple_choices/questionnaires_controller.rb, app/controllers/pages_controller.rb, app/controllers/peer_review/challenges_controller.rb, app/controllers/stats_controller.rb, app/presenters/layout/menu_presenter.rb, app/views/multiple_choices/questionnaires/index.html.erb, app/views/pages/welcome.html.erb, app/views/peer_review/challenges/index.html.erb, app/views/stats/points.html.erb
Ref: [Trello](https://trello.com/c/35VcqdmK/426-b4-faltantes)
=> Bootstrap 4 for student pages

app/controllers/admin/courses_controller.rb, app/controllers/application_controller.rb, app/models/course.rb, app/models/user.rb, app/views/admin/courses/index.html.erb, config/routes.rb, lib/course_lock.rb
Ref: [Trello](https://trello.com/c/DkYkmMqR/72-migrar-elementos-de-un-curso-a-otro)
Este feature es re necesario para armar los cursos que sean idénticos a cursos anteriores. Me centré en los features que ya tenemos, para copiar lo mínimo. A medida que habilitemos herramientas, copio más cosas.
Me interesa una revisión porque puedo haberle pifiado a algo.
=> Duplicate courses, chapter 1

.githooks/pre-commit, .rubocop.yml, app/controllers/peer_review/challenges_controller.rb, app/controllers/peer_review/reviews_controller.rb, app/models/peer_review/challenge.rb, app/models/peer_review/review.rb, app/views/peer_review/_review_rubrics.html.haml, app/views/peer_review/challenges/form.html.erb, app/views/peer_review/challenges/show.html.erb, app/views/peer_review/reviews/new.html.erb, app/views/peer_review/solutions/show.html.erb, config/initializers/simple_form.rb, db/migrate/20200902220953_add_rubric_to_challenge.rb, db/schema.rb
Ref: https://trello.com/c/ZNPiYM85/403-rubricas-de-correccion-guiadas-para-los-desafios
=> Rubrics for peer review challenges

app/assets/javascripts/application2.js, app/assets/stylesheets/application2.css, app/controllers/dashboard_controller.rb, app/controllers/multiple_choices/questionnaires_controller.rb, app/controllers/peer_review/challenges_controller.rb, app/controllers/peer_review/reviews_controller.rb, app/models/peer_review/challenge.rb, app/presenters/layout/menu_presenter.rb, app/views/dashboard/index.html.haml, app/views/multiple_choices/questionnaires/index.html.erb, app/views/peer_review/_review_rubrics.html.haml, app/views/peer_review/challenges/form.html.erb, app/views/peer_review/reviews/new.html.erb, app/views/peer_review/solutions/new.html.erb, vendor/assets/components/codemirror/mode/python/python.js
[1](https://trello.com/c/uW7tVBSl/444-el-codigo-deberia-verse-bien), [2](https://trello.com/c/DFnaARRY/441-mch-deberian-aparecer-despublicados-agregarlo-en-una-columna-para-verlo-como-en-los-prch), [3](https://trello.com/c/4YPSY6iM/440-agregar-mch-en-el-tablero), [4](https://trello.com/c/b7nk7h8O/443-falla-al-crear-tareas-sin-rubricas), [5](https://trello.com/c/I269cg5S/429-syntax-python).
=> Various issues, 3rd batch

app/controllers/multiple_choices/questionnaires_controller.rb, app/models/multiple_choices/answer.rb, app/models/multiple_choices/question.rb, app/models/multiple_choices/solution.rb, app/presenters/multiple_choices/practice_questionnaire_presenter.rb, app/presenters/multiple_choices/question_stats.rb, app/presenters/multiple_choices/solved_questionnaire_presenter.rb, app/views/multiple_choices/questionnaires/form.html.erb, app/views/multiple_choices/questionnaires/index.html.erb, app/views/multiple_choices/questionnaires/overview.html.erb, db/migrate/20200930134608_add_hidden_to_multiple_choice_question.rb, db/schema.rb
Many tasks at once, all tending to enhance Multiple Choices:
- Display student's response on each question
- Added question number when editing the questionnaire
- Duplicate question/answer
- Hidden questions
- Better overview
- Stats: # of answers for each response
- Removed .where, used scopes
=> MultipleChoice enhancements

app/assets/stylesheets/application2.css, app/controllers/students_controller.rb, app/controllers/users_controller.rb, app/views/students/edit.html.haml, app/views/students/index.html.erb, app/views/users/show.html.erb, config/routes.rb, lib/tasks/fix_usernames.rake
Queremos diferenciar las acciones de usuario, de las acciones de estudiante. Esto nos permitirá que el rol docente pueda efectuar acciones sobre el estudiante, sin interferir con el usuario, realizando acciones sobre sí mismo.
=> Move students actions out of users_controller
